Repository projectdiscovery/httpx, pull requests merged in 2020-12, with the labels that each got.

#167 Improve GBK encode
  common/httpx/title.go
Labels: Status: Completed, Type: Enhancement

#172 fixing cross-compilation
  go.mod
  go.sum
Labels: Type: Bug

#178 fix charset gbk and gb2312
  common/httpx/title.go
Labels: Status: Accepted

#181 Improved title extraction
  common/httpx/title.go
Labels: Status: Review Needed, Type: Bug
