Repository projectdiscovery/httpx, pull requests merged in 2020-08, with the labels that each got.

#59 updating go modules
  go.mod
  go.sum
Labels: bug

#68 Various fixes and features
  cmd/httpx/httpx.go
  common/httputilz/httputilz.go
  common/httpx/csp.go
  common/httpx/httpx.go
  common/httpx/option.go
  common/httpx/response.go
  common/iputil/iputil.go
  go.mod
  go.sum
Labels: Status: Review Needed, bug, enhancement

#71 adding errors to output in debug mode
  cmd/httpx/httpx.go
Labels: Status: Completed

#74 fixing uripath
  cmd/httpx/httpx.go
  common/httpx/httpx.go
  common/httpx/option.go
  go.mod
  go.sum
Labels: bug

#75 all: simplify logic statements and remove unneeded conversions
  common/cache/dialer.go
  common/customports/customport.go
  common/fileutil/fileutil.go
  common/httpx/httpx.go
  common/iputil/iputil.go
Labels: Status: In Progress

#79 adding http2 slow probe
  cmd/httpx/httpx.go
  common/httpx/http2.go
  common/httpx/httpx.go
  common/httpx/response.go
  go.mod
  go.sum
Labels: Status: Completed

#82 adding multi-verb support
  cmd/httpx/httpx.go
Labels: Status: Completed

#80 adding http pipeline check
  cmd/httpx/httpx.go
  common/httpx/pipeline.go
  go.mod
  go.sum
Labels: Status: Revision Needed
