Repository projectdiscovery/httpx, pull requests merged in 2020-11, with the labels that each got.

#156 Improved readability and error handling on customport.go
  common/customports/customport.go
Labels: Status: Review Needed

#161 adding hmap (input dedupe) + wip clistats
  cmd/httpx/httpx.go
  common/customports/customport.go
  go.mod
  go.sum
  internal/runner/options.go
  internal/runner/runner.go
  internal/runner/util.go
Labels: Status: Review Needed, Type: Enhancement

#155 adding fastdialer
  common/cache/cache.go
  common/cache/dialer.go
  common/cache/doc.go
  common/httpx/httpx.go
  common/resolve/client.go
  common/resolve/doc.go
  common/resolve/utils.go
  go.mod
  go.sum
  internal/runner/runner.go
Labels: Status: Review Needed, Type: Enhancement

#166 updating fast dialer module
  go.mod
  go.sum
Labels: Type: Bug
