Repository projectdiscovery/httpx, pull requests merged in 2020-07, with the labels that each got.

#39 using ld compiler
  .github/workflows/release.yml
Labels: bug

#32 Update title.go
  common/httpx/title.go
Labels: enhancement

#45 fixing host header
  cmd/httpx/httpx.go
  common/httpx/httpx.go
Labels: bug

#46 fixed automatic decoding
  common/httpx/encodings.go
  common/httpx/httpx.go
  common/httpx/title.go
  go.mod
  go.sum
Labels: bug

#48 TLS data extraction for HTTPS
  cmd/httpx/httpx.go
  common/httpx/httpx.go
  common/httpx/response.go
  common/httpx/tls.go
Labels: Status: Review Needed

#50 request path option
  cmd/httpx/httpx.go
Labels: Status: Review Needed

#52 updating output flags
  cmd/httpx/httpx.go
  common/fileutil/fileutil.go
  common/httpx/response.go
  common/slice/slice.go
  common/stringz/stringz.go
Labels: Status: In Progress, bug

#55 content-type fix with no color
  cmd/httpx/httpx.go
Labels: Status: Review Needed, bug
