Repository projectdiscovery/httpx, pull requests merged in 2020-09, with the labels that each got.

#86 fix and improve method CLI option
  cmd/httpx/httpx.go
  common/httputilz/methods.go
  common/stringz/stringz.go
Labels: Status: Completed

#89 updating go modules
  go.mod
  go.sum
Labels: Status: Review Needed, bug

#104 extended CSP extraction
  common/httpx/csp.go
  common/slice/slice.go
  go.mod
  go.sum
Labels: Status: Completed

#105 adding output ip
  cmd/httpx/httpx.go
  common/cache/dialer.go
Labels: Status: Review Needed, enhancement

#103 adding fdmax
  cmd/httpx/httpx.go
  go.mod
  go.sum
Labels: Status: Completed

#109 adding cdn check
  cmd/httpx/httpx.go
  common/httpx/cdn.go
  common/httpx/httpx.go
  go.mod
  go.sum
Labels: Status: Completed

#108 adding cname + ips lookup in global cache
  cmd/httpx/httpx.go
  common/cache/cache.go
  common/cache/dialer.go
  common/cache/utils.go
  common/resolver/client.go
Labels: Status: Review Needed

#110 adding string/regex match/filter
  cmd/httpx/httpx.go
Labels: Status: Review Needed

#113 avoid fatal on store response error
  cmd/httpx/httpx.go
Labels: Status: Completed

#119 small code refactor
  common/cache/cache.go
  go.mod
  go.sum
Labels: Type: Bug

#120 improved regex title
  common/httpx/title.go
Labels: Type: Bug

#121 Add golangci-lint to the current GitHub workflow
  .github/workflows/build.yaml
  .golangci.yml
  cmd/httpx/httpx.go
  common/cache/cache.go
  common/cache/dialer.go
  common/cache/doc.go
  common/customheader/doc.go
  common/customports/customport.go
  common/customports/doc.go
  common/fileutil/doc.go
  common/httputilz/doc.go
  common/httputilz/httputilz.go
  common/httputilz/methods.go
  common/httpx/csp.go
  common/httpx/doc.go
  common/httpx/encodings.go
  common/httpx/http2.go
  common/httpx/httpx.go
  common/httpx/option.go
  common/httpx/pipeline.go
  common/httpx/response.go
  common/httpx/tls.go
  common/httpx/virtualhost.go
  common/iputil/doc.go
  common/resolve/client.go
  common/resolve/doc.go
  common/resolve/utils.go
  common/slice/doc.go
  common/stringz/doc.go
  common/stringz/stringz.go
Labels: Status: Accepted, Type: Enhancement

#122 Handle data from char device on stdin
  common/fileutil/fileutil.go
Labels: Status: Accepted, Type: Bug

#127 adding automatic content-length
  cmd/httpx/httpx.go
Labels: Priority: Low, Status: Accepted, Type: Bug

#126 adding response time
  cmd/httpx/httpx.go
  common/httpx/httpx.go
  common/httpx/response.go
  go.mod
  go.sum
Labels: Priority: Low, Status: Accepted, Type: Enhancement
