Repository projectdiscovery/httpx, pull requests merged in 2021-07, with the labels that each got.

#323 [Feature] Adding new status flag
  runner/banner.go
  runner/options.go
  runner/runner.go
Labels: Status: Completed, Type: Enhancement

#326 Small logic refactor
  .golangci.yml
  runner/options.go
  runner/runner.go
Labels: Type: Bug, Type: Maintenance

#327 Updating deps
  go.mod
  go.sum
Labels: Status: Completed, Type: Maintenance

#330 Issue#315-rate-limit-support
  go.mod
  go.sum
  runner/options.go
  runner/runner.go
Labels: enhancement
