Repository projectdiscovery/httpx, pull requests merged in 2021-05, with the labels that each got.

#250 Adding correct helper to dump raw http requests
  go.mod
  go.sum
  internal/runner/runner.go
Labels: Type: Bug

#252 adding glob support
  common/fileutil/fileutil.go
  go.mod
  go.sum
  internal/runner/options.go
  internal/runner/runner.go
Labels: Type: Enhancement

#256 replacing iputil with shared library
  common/iputil/doc.go
  common/iputil/iputil.go
  go.mod
  go.sum
  internal/runner/runner.go
Labels: Type: Maintenance

#261 Making runner public
  cmd/httpx/httpx.go
  runner/banner.go
  runner/doc.go
  runner/options.go
  runner/runner.go
Labels: Type: Maintenance

#251 Adding support for redirect chain dump
  common/httputilz/httputilz.go
  common/httputilz/methods.go
  common/httpx/httpx.go
  common/httpx/response.go
  go.mod
  go.sum
  runner/options.go
  runner/runner.go
Labels: Type: Enhancement

#263 Bugfix tlsprobe autoenable tlsgrag
  runner/runner.go
Labels: Type: Bug

#267 adding final url support
  common/httpx/response.go
  go.mod
  go.sum
  runner/runner.go
Labels: Type: Enhancement

#273 Add default port for URL to solve automatic use of HTTP
  common/stringz/stringz.go
  go.mod
  go.sum
  runner/runner.go
Labels: Status: Review Needed, Type: Enhancement

#272 Improving certificate parsing
  common/httpx/tls.go
Labels: Status: Revision Needed

#282 Fixing full URL parsing
  .github/workflows/build.yaml
  .golangci.yml
  common/httputilz/httputilz.go
  common/httpx/csp.go
  common/httpx/title.go
  common/stringz/stringz.go
  go.mod
  go.sum
  runner/runner.go
Labels: Status: Completed, bug

#284 [Bug] http2 compatibility
  go.mod
  go.sum
Labels: bug

#285 Fixing behavior causing 307/308 failure
  runner/runner.go
Labels: Status: Review Needed, bug

#287 Fixing fallback logic
  common/stringz/stringz.go
  runner/options.go
  runner/runner.go
Labels: bug
