Repository projectdiscovery/httpx, pull requests merged in 2021-08, with the labels that each got.

#340 Adding support for non-ascii characters in path for unsafe requests
  go.mod
  go.sum
  runner/runner.go
Labels: Type: Bug

#346 issue-325-max-response-body-size
  common/httpx/httpx.go
  common/httpx/option.go
  runner/options.go
  runner/runner.go
Labels: Type: Enhancement

#344 [Bugfix] Improving stats calculation
  runner/runner.go
Labels: Status: Completed, Type: Bug

#343 Moving tls parsing code to shared library (cryptoutil - used also by fastdialer)
  common/httpx/response.go
  common/httpx/tls.go
  go.mod
  go.sum
  runner/runner.go
Labels: Type: Maintenance

#338 [Feature] Adding support to scan only ports 80/443 if the ip is part of CDN range
  common/httpx/httpx.go
  common/httpx/option.go
  runner/options.go
  runner/runner.go
Labels: enhancement, Status: Revision Needed

#345 Adding stop-resume support
  cmd/httpx/httpx.go
  go.mod
  go.sum
  runner/options.go
  runner/resume.go
  runner/runner.go
Labels: Status: Completed, Type: Enhancement

#351 Small change in output stats
  runner/runner.go
Labels: Type: Maintenance

#352 Fixing error in logic
  runner/runner.go
Labels: Type: Maintenance

#360 Improving rawhttp timeout handling
  common/httpx/httpx.go
  go.mod
  go.sum
Labels: Type: Bug

#361 Upgrading fastdialer with better error message on denied ips
  go.mod
  go.sum
Labels: Type: Bug

#358 Adding option to skip remaining paths on unresponsive host
  go.mod
  go.sum
  runner/options.go
  runner/runner.go
Labels: Status: Review Needed, Type: Enhancement

#365 Adding support for maximum redirects number
  common/httpx/httpx.go
  common/httpx/option.go
  runner/options.go
  runner/runner.go
Labels: Type: Enhancement

#369 Improving case behavior with methods CLI option
  common/httpx/httpx.go
  go.mod
  go.sum
  runner/options.go
  runner/runner.go
Labels: Type: Bug

#366 Fixing inconsistent "input" field behavior
  runner/runner.go
Labels: Type: Bug

#367 Fixing inconsistent behavior for custom ports with schemes
  common/customports/customport.go
  common/httpx/http2.go
  go.mod
  go.sum
  runner/runner.go
Labels: Type: Bug

#376 Improving cli parsing for Allow/Deny option
  README.md
  common/customlist/customlist.go
  common/fileutil/fileutil.go
  go.mod
  go.sum
  runner/options.go
  runner/runner.go
Labels: Type: Bug

#375 Fixing input URLs handling with non-rfc paths
  common/httpx/httpx.go
  common/httpx/option.go
  common/httpx/virtualhost.go
  common/stringz/stringz.go
  runner/runner.go
Labels: Type: Bug

#379 Adding integration/regression tests
  .github/workflows/build-test.yml
  .gitignore
  cmd/integration-test/http.go
  cmd/integration-test/integration-test.go
  go.mod
  go.sum
  integration_tests/run.sh
  internal/testutils/integration.go
Labels: Type: Enhancement, Type: Maintenance
