Repository projectdiscovery/httpx, pull requests merged in 2021-11, with the labels that each got.

#436 Functional test
  .github/workflows/functional-test.yml
  .gitignore
  cmd/functional-test/main.go
  cmd/functional-test/run.sh
  cmd/functional-test/test-data/raw-request.txt
  cmd/functional-test/test-data/request.txt
  cmd/functional-test/testcases.txt
  internal/testutils/integration.go
Labels: Status: Review Needed, Type: Enhancement

#439 Fix npe on debug output
  runner/runner.go
Labels: Type: Bug

#448 New line with title flag
  cmd/integration-test/http.go
  common/httpx/title.go
Labels: Status: Review Needed, Type: Bug
