Repository projectdiscovery/httpx, pull requests merged in 2022-11, with the labels that each got.

#847 Updating httpx as a library integration test
  cmd/integration-test/library.go
Labels: Type: Maintenance

#859 Fixing content length bytes count
  common/httpx/httpx.go
  common/httpx/httpx_test.go
Labels: Type: Bug

#853 Add delay between making httpx requests.
  README.md
  runner/options.go
  runner/runner.go
Labels: Status: Review Needed

#848 Use a random hash instead of generating an url-based filename to store
  runner/options.go
  runner/runner.go
Labels: Type: Bug

#885 adds base64 encoding support (#813)
  common/stringz/stringz.go
  runner/options.go
  runner/runner.go
Labels: Type: Enhancement

#887 bom utf8 on csv output
  runner/options.go
  runner/runner.go
Labels: Type: Bug
