Repository projectdiscovery/httpx, pull requests merged in 2022-01, with the labels that each got.

#470 Enabling store response automatically if output directory is specified
  README.md
  runner/options.go
Labels: Status: Review Needed, Type: Enhancement

#468 Adding support for lines/words matchers/filters
  README.md
  runner/options.go
  runner/runner.go
Labels: Type: Enhancement

#471 Adding CLI option to trim default HTTP/HTTPS ports from Host header
  runner/options.go
  runner/runner.go
Labels: Status: Completed, Type: Enhancement

#476 Add support for favicon hash
  README.md
  common/slice/slice.go
  common/stringz/stringz.go
  go.mod
  go.sum
  runner/options.go
  runner/runner.go
Labels: Status: Completed, Type: Enhancement

#483 Improving paths loading from file
  cmd/integration-test/http.go
  runner/runner.go
Labels: Status: Review Needed, Type: Bug

#490 ratelimit per min support
  README.md
  runner/options.go
  runner/runner.go
Labels: Status: Review Needed, Type: Enhancement

#500 Added stats-interval for changing stats display frequency
  runner/options.go
  runner/runner.go
Labels: Status: Review Needed

#504 stat flag timer
  runner/runner.go
Labels: Status: Review Needed, Type: Bug

#507 Update options.go
  runner/options.go
Labels: Type: Bug
