Repository projectdiscovery/httpx, pull requests merged in 2022-02, with the labels that each got.

#510 Adding support for euc-kr charset
  common/httpx/encodings.go
  common/httpx/title.go
Labels: Status: Review Needed, Type: Bug

#499 Expose CDN Name in output and json
  common/httpx/cdn.go
  go.mod
  go.sum
  runner/runner.go
Labels: Status: Review Needed

#514 Updating GH workflows + Sonar
  .github/dependabot.yml
  .github/workflows/build-test.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/functional-test.yml
  .github/workflows/release-binary.yml
  .github/workflows/sonarcloud.yml
  cmd/functional-test/run.sh
  integration_tests/run.sh
  sonar-project.properties
Labels: Status: Review Needed, Type: Maintenance

#526 Regression tests on windows OS
  .github/workflows/build-test.yml
Labels: Status: Review Needed, Type: Bug
