Repository projectdiscovery/httpx, pull requests merged in 2022-04, with the labels that each got.

#561 Adding custom cookies supports in redirects
  common/httpx/httpx.go
  common/httpx/option.go
Labels: Status: Review Needed, Type: Bug

#562 Issue 495 ASN support
  go.mod
  go.sum
  runner/options.go
  runner/runner.go
Labels: Status: Review Needed, Type: Enhancement

#567 Issue 549 jarm algorithm
  README.md
  common/hashes/hashes.go
  common/hashes/jarmhash.go
  common/regexhelper/regex.go
  go.mod
  go.sum
  runner/options.go
  runner/runner.go
Labels: Status: Review Needed, Type: Enhancement

#579 Match/filter cdn
  README.md
  go.mod
  go.sum
  runner/options.go
  runner/runner.go
Labels: Status: Review Needed, Type: Enhancement

#581 Adding support for custom SNI name
  common/httpx/httpx.go
  common/httpx/option.go
  go.mod
  go.sum
  runner/options.go
  runner/runner.go
Labels: Status: Review Needed, Type: Enhancement

#595 Disable static compilation for osx
  Makefile
Labels: Status: Review Needed, Type: Maintenance
