Repository projectdiscovery/httpx, pull requests merged in 2022-06, with the labels that each got.

#650 changed warning to error if the directory does not have write permission
  runner/runner.go
Labels: Status: Review Needed, Type: Bug

#646 updates from urlutil library
  go.mod
  go.sum
Labels: Status: Review Needed, Type: Bug

#663 Fixing wrong app name
  cmd/functional-test/run.sh
  sonar-project.properties
Labels: Type: Maintenance

#665 Add self diagnostic functionality
  go.mod
  go.sum
  runner/healthcheck.go
  runner/options.go
Labels: Status: Review Needed, Type: Maintenance

#673 Improving HTML decoding
  common/httpx/encodings.go
  common/httpx/httpx.go
  common/httpx/title.go
  go.sum
Labels: Status: Review Needed, Type: Bug

#667 Using scanme.sh in functional tests + Fixing gosec action error
  .github/workflows/sonarcloud.yml
  cmd/functional-test/test-data/request.txt
  cmd/functional-test/testcases.txt
Labels: Status: Review Needed, Type: Maintenance

#670 Adding httpx as a library minimal example
  README.md
  cmd/integration-test/integration-test.go
  cmd/integration-test/library.go
  runner/options.go
Labels: documentation, Type: Enhancement

#668 Exposing regex matches to json output
  runner/runner.go
Labels: Type: Bug
