Repository projectdiscovery/httpx, pull requests merged in 2022-07, with the labels that each got.

#676 Removing redundant regex in jarm calculation
  common/hashes/jarmhash.go
  common/regexhelper/regex.go
Labels: Status: Review Needed, Type: Maintenance

#677 modified error message with invalid ports
  common/customports/customport.go
  runner/options.go
  runner/runner.go
Labels: Status: Review Needed, Type: Bug

#689 Update go.mod
  common/hashes/jarmhash.go
  go.mod
  go.sum
  runner/runner.go
Labels: Status: Review Needed, Type: Bug

#687 Fix for -er and -favicon.
  runner/options.go
Labels: Type: Bug

#694 Merging Master into dev-merge-master
  runner/runner.go
Labels: Type: Maintenance

#707 Added connection pooling for jarm conn + fastdialer
  common/hashes/jarm/connpool.go
  common/hashes/jarm/jarmhash.go
  common/hashes/jarm/onetimepool.go
  common/hashes/jarmhash.go
  go.mod
  go.sum
  runner/runner.go
Labels: Status: Review Needed

#714 Fixing and improving custom ports handling
  cmd/functional-test/testcases.txt
  common/customports/customport.go
  runner/options.go
Labels: Status: Review Needed, Type: Bug
