Repository projectdiscovery/httpx, pull requests merged in 2022-08, with the labels that each got.

#718 favicon flag improvement
  runner/options.go
  runner/runner.go
Labels: Status: Review Needed, Type: Enhancement

#726 Minor fixes and improvements
  .gitignore
  README.md
  cmd/integration-test/http.go
  common/customextract/customextract.go
  common/fileutil/fileutil.go
  common/httputilz/httputilz.go
  common/httpx/encodings.go
  common/httpx/http2.go
  common/httpx/httpx.go
  go.mod
  go.sum
  runner/options.go
  runner/runner.go
Labels: Type: Enhancement

#738 Added profile-mem flag for memory profiling
  cmd/httpx/httpx.go
  runner/options.go
Labels: Status: Review Needed
