Repository projectdiscovery/httpx, pull requests merged in 2023-09, with the labels that each got.

#1316 Add flag to preview first N characters
  README.md
  cmd/functional-test/testcases.txt
  common/httputilz/normalize.go
  common/httpx/httpx.go
  go.mod
  go.sum
  runner/options.go
  runner/runner.go
  runner/types.go
Labels: Type: Enhancement

#1335 Redirect policy with hsts
  README.md
  common/httpx/httpx.go
  common/httpx/option.go
  runner/options.go
  runner/runner.go
Labels: Status: Review Needed

#1347 Fixed DNS resolving A records when -ports is set
  runner/runner.go
Labels: Type: Bug

#1360 Restoring https://github.com/projectdiscovery/httpx/pull/1331
  README.md
  runner/options.go
  runner/runner.go
Labels: Type: Enhancement

#1364 add phash calculation for screenshot
  go.mod
  go.sum
  runner/runner.go
Labels: Type: Enhancement
